format_version: 10
pipelines:
  prometheus:
    group: Tools
    materials:
      git-da613e5:
        git: https://github.com/Devopslearningvamshi/tool-automation_mointoring.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - ansible:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                 - exec: {command: ansible-playbook, arguments: [ "-i", "172.31.91.151,","tool.yml", "-e", "tool_name=prometheus", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321"], run_if: passed}